#!/usr/bin/env python3
"""
ext-sort
Desc: A utility that sorts files based on their extension
v.0.1
2020 by radicalarchivist

Usage:
  ext-sort [-ckr] -x EXTENSION SCAN-DIR TARGET-DIR
  ext-sort --help
  ext-sort --version

Options:
  SCAN-DIR                              Directory to be scanned
  TARGET-DIR                            Directory to copy files into
  -x --extension EXTENSION              extension(s) of the files to move
  -r --recursive                        Scan recursively
  -k --keep-structure                   Retains directory structure when moving
  -c --cron                             Used when ext-sort is run on a schedule, assumes yes to prompts
  -h --help                             Show this screen
  --version                             Show version info

"""

#
# TODO:
#
#

from docopt import docopt
from .funcs import yn_prompt,get_filelist,move_files

def main(args):
    print(f"""Moving files with extension(s) {args['--extension']} from {args['SCAN-DIR']} to {args['TARGET-DIR']}
Recursive Mode: {('On' if args['--recursive'] else 'Off')}
Keep File Structure: {args['--keep-structure']}
Scanning {args['SCAN-DIR']}""",end="...",flush=True)
    filelist = get_filelist(args['SCAN-DIR'],args['--extension'].split(','),args['--recursive'])
    print("Done.",flush=True)
    if not len(filelist):
        print(f"No files were found with the extension(s): {args['--extension']}")
        exit()
    print(f"Found {len(filelist)} files with the extension(s): {args['--extension']}")
    if not args['--cron']:
        if not yn_prompt(f"Do you wish to move the files to {args['TARGET-DIR']}?"): 
            print("Operation cancelled.",flush=True)
            exit()
    print(f"Moving files to {args['TARGET-DIR']}...",flush=True)
    move_files(filelist,args['SCAN-DIR'],args['TARGET-DIR'],args['--keep-structure'])

if __name__ == "__main__":
    main(docopt(__doc__, version='ext-sort v.0.1'))
    print("Operation Complete.",flush=True)
    exit()